name: roman-check
on: 
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checks out your repository
        uses: actions/checkout@v2
      - name: start linter
        run: python3 -m flake8 brain_games