name: roman-check
on: 
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out your repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: make install
      - name: Start linter
        run: make lint